### ISSUE TITLE
Problem with zoltan

### ISSUE THREAD

**Issue by Anmol1696** [Anmol1696/pysph_docker#4]
Traceback (most recent call last):
  File "/pysph/setup.py", line 482, in <module>
    setup_package()
  File "/pysph/setup.py", line 404, in setup_package
    create_sources()
  File "/pysph/setup.py", line 393, in create_sources
    print(check_output(cmd).decode())
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'pyzoltan/core/generator.py', '/pyzoltan/core']' returned non-zero exit status 2

**Comment by Anmol1696** [comment]
i think the problem is not in zoltan but in setup.py
